# Generated by Django 2.1.3 on 2018-12-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('icone', models.ImageField(default='img/default.jpg', upload_to='img')),
                ('resume', models.TextField(null=True)),
                ('video', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('icone_a', models.ImageField(default='img/default.jpg', upload_to='img')),
                ('icone_b', models.ImageField(default='img/default.jpg', upload_to='img')),
                ('icone_c', models.ImageField(default='img/default.jpg', upload_to='img')),
                ('niveau', models.IntegerField(default=0)),
                ('rang', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Cours')),
            ],
            options={
                'verbose_name': 'Les modules',
                'ordering': ['niveau', 'rang'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vraifaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
