# Generated by Django 2.1.3 on 2018-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.IntegerField(default=0),
        ),
    ]
