# Generated by Django 2.1.3 on 2018-12-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_cours_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='langue',
            field=models.CharField(default='fr', max_length=10),
        ),
    ]
