# Generated by Django 2.1.3 on 2018-12-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_cours_langue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='icone_a',
            new_name='icone_0',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='icone_b',
            new_name='icone_1',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='icone_c',
            new_name='icone_2',
        ),
    ]
