# Generated by Django 2.1.3 on 2018-12-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_auto_20181213_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='video',
        ),
    ]
