# Generated by Django 2.1.3 on 2018-12-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_qcm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['id'], 'verbose_name': 'Cours'},
        ),
    ]
