# Generated by Django 2.1.3 on 2018-12-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.IntegerField(default=1)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermodule', to='cours.Cours')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profils.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.IntegerField(default=1)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermodule', to='cours.Module')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profils.Profil')),
            ],
        ),
        migrations.AlterField(
            model_name='achievement',
            name='members',
            field=models.ManyToManyField(through='profils.UserAchiev', to='profils.Profil'),
        ),
        migrations.AddField(
            model_name='profil',
            name='cours',
            field=models.ManyToManyField(through='profils.UserCours', to='cours.Cours'),
        ),
        migrations.AddField(
            model_name='profil',
            name='modules',
            field=models.ManyToManyField(through='profils.UserModule', to='cours.Module'),
        ),
    ]
