# Generated by Django 2.1.3 on 2018-12-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0002_auto_20181211_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercours',
            name='niveau',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='members',
            field=models.ManyToManyField(through='profils.UserAchiev', to='profils.Profil'),
        ),
        migrations.AlterField(
            model_name='usercours',
            name='solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodule',
            name='solved',
            field=models.IntegerField(default=0),
        ),
    ]
