# Generated by Django 2.1.3 on 2018-12-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0003_auto_20181214_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='members',
            field=models.ManyToManyField(through='profils.UserAchiev', to='profils.Profil'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
