# Generated by Django 2.1.3 on 2018-12-20 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0006_auto_20181220_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='members',
            field=models.ManyToManyField(through='profils.UserAchiev', to='profils.Profil'),
        ),
        migrations.AlterField(
            model_name='usercours',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercours', to='cours.Cours'),
        ),
    ]
