# Generated by Django 2.1.3 on 2018-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0008_auto_20181220_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='members',
            field=models.ManyToManyField(through='profils.UserAchiev', to='profils.Profil'),
        ),
    ]
